image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent
replicaCount: 3
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  className: ""
  hosts:
    - host: microservice.local
      paths:
        - path: /
          pathType: Prefix
  tls: []
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
postgresql:
  enabled: true
  storageClassName: ebs-gp3-ha
  storageSize: 20Gi
  image: postgres:15-alpine
  username: appuser
  database: appdb
  existingSecret: postgres-app-secret
securityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101
nodeSelector: {}
tolerations: []
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: microservice-frontend
podDisruptionBudget:
  minAvailable: 2
autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
