{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
type: Opaque
stringData:
  username: {{ .Values.postgresql.username | default "appuser" }}
  password: {{ randAlphaNum 32 | quote }}
{{- end }}
